from __future__ import annotations

import json

import numpy as np
import pandas as pd

from nba_impact.models.rapm import RapmConfig, build_design, fit_coefficients
from nba_impact.models.rapm_uncertainty import (
    RapmUncertaintyConfig,
    _draw_weights,
    fit_weighted_zero_prior,
    game_cluster_sandwich,
    run_rapm_uncertainty,
)


def _frame() -> pd.DataFrame:
    rng = np.random.default_rng(41)
    rows = []
    for season in (2024, 2025):
        for game in range(4):
            for possession in range(12):
                away = [1, 2, 3, 4, 5]
                home = [6, 7, 8, 9, 10]
                # A cameo player makes missing-draw handling observable.
                if season == 2025 and game == 3:
                    home[0] = 11
                home_poss = bool(possession % 2)
                rows.append(
                    {
                        "home_poss": home_poss,
                        "pts": 1.05 + 0.03 * home_poss + rng.normal(0, 0.1),
                        **{f"a{i + 1}": value for i, value in enumerate(away)},
                        **{f"h{i + 1}": value for i, value in enumerate(home)},
                        "season": season,
                        "date": f"{season - 1}-11-01",
                        "period": 1,
                        "num": possession + 1,
                        "gameid": f"002{season}{game:04d}",
                    }
                )
    return pd.DataFrame(rows)


def test_weighted_one_fit_matches_frozen_point_estimator() -> None:
    design = build_design(_frame())
    config = RapmConfig(seasons=(2024, 2025), lambda_off=30, lambda_def=30, lambda_home=5)
    expected_beta, expected_intercept = fit_coefficients(design, config)
    beta, intercept, _, _, _ = fit_weighted_zero_prior(design, config)
    np.testing.assert_allclose(beta, expected_beta, atol=1e-10)
    assert intercept == expected_intercept


def test_draw_weights_are_game_whole_and_season_stratified() -> None:
    design = build_design(_frame())
    weights, counts = _draw_weights(design, 9, 4)
    assert counts == {"2024": 4, "2025": 4}
    for season in (2024, 2025):
        rows = np.flatnonzero(design.seasons == season)
        for game in np.unique(design.game_ids[rows]):
            game_weights = weights[rows[design.game_ids[rows] == game]]
            assert len(set(game_weights)) == 1


def test_sandwich_recentering_and_net_covariance_are_joint() -> None:
    design = build_design(_frame())
    config = RapmConfig(seasons=(2024, 2025), lambda_off=30, lambda_def=30, lambda_home=5)
    covariance, beta, _ = game_cluster_sandwich(design, config)
    n_players = len(design.players)
    assert np.allclose(covariance, covariance.T)
    np.testing.assert_allclose(
        np.average(beta[:n_players], weights=design.off_possessions), 0.0, atol=1e-12
    )
    np.testing.assert_allclose(
        np.average(beta[n_players : 2 * n_players], weights=design.def_possessions), 0.0, atol=1e-12
    )
    net_variance = (
        np.diag(covariance)[:n_players]
        + np.diag(covariance)[n_players : 2 * n_players]
        - 2 * np.diag(covariance[:n_players, n_players : 2 * n_players])
    )
    assert np.isfinite(net_variance).all()


def test_bootstrap_resume_repairs_deleted_draw_and_preserves_component_identity(tmp_path) -> None:
    frame = _frame()
    config = RapmConfig(seasons=(2024, 2025), lambda_off=30, lambda_def=30, lambda_home=5)
    uncertainty = RapmUncertaintyConfig(draws=8, seed=77)
    first = run_rapm_uncertainty(frame, config, uncertainty, artifact_root=tmp_path)
    root = tmp_path / "models" / "rapm_uncertainty" / first["run_id"]
    missing = root / "bootstrap_draws" / "draw_0003.parquet"
    missing.unlink()
    second = run_rapm_uncertainty(frame, config, uncertainty, artifact_root=tmp_path)
    assert second["run_id"] == first["run_id"]
    assert missing.exists()
    ratings = pd.read_parquet(root / "ratings_uncertainty.parquet")
    np.testing.assert_allclose(
        ratings["net_estimate"], ratings["offense_estimate"] + ratings["defense_estimate"], atol=1e-10
    )
    assert (ratings["net_draw_coverage"] <= uncertainty.draws).all()
    metadata = json.loads((root / "bootstrap_draws" / "draw_0003.json").read_text())
    assert metadata["draw"] == 3


def test_synthetic_whole_game_bootstrap_has_nominal_directional_coverage() -> None:
    """Check the interval method against a known regularized estimand.

    This is not a claim that NBA ratings are generated by this simulator. It
    catches regressions such as resampling possession rows instead of games,
    losing common game shocks, or forming net intervals from marginal draws.
    The target is the noiseless *regularized and recentered* coefficient, so
    ridge shrinkage is part of the estimand rather than a hidden coverage bias.
    """
    rng = np.random.default_rng(20260812)
    rows = []
    for game in range(192):
        away = [1 + (game + offset) % 8 for offset in range(5)]
        home = [9 + (2 * game + offset) % 8 for offset in range(5)]
        for possession in range(12):
            rows.append(
                {
                    "home_poss": bool(possession % 2),
                    "pts": 0.0,
                    **{f"a{i + 1}": value for i, value in enumerate(away)},
                    **{f"h{i + 1}": value for i, value in enumerate(home)},
                    "season": 2025,
                    "date": "2024-11-01",
                    "period": 1,
                    "num": possession + 1,
                    "gameid": f"0022025{game:04d}",
                }
            )
    base = pd.DataFrame(rows)
    config = RapmConfig(seasons=(2025,), lambda_off=30, lambda_def=30, lambda_home=5)
    base_design = build_design(base)
    n_players = len(base_design.players)
    raw_coefficients = np.concatenate(
        [
            np.linspace(-0.025, 0.035, n_players),
            np.linspace(0.022, -0.020, n_players),
            np.array([0.010]),
        ]
    )
    expected_points = 1.08 + np.asarray(base_design.X @ raw_coefficients).ravel()
    noiseless = base.copy()
    noiseless["pts"] = expected_points
    target = fit_weighted_zero_prior(build_design(noiseless), config)[0]
    player_index = int(np.flatnonzero(base_design.players == 1)[0])

    covered = np.zeros(4, dtype=int)  # offense 80/95, net 80/95
    repetitions, draws = 24, 160
    for repetition in range(repetitions):
        frame = base.copy()
        game_shock = {
            game_id: rng.normal(0.0, 0.15) for game_id in frame["gameid"].unique()
        }
        frame["pts"] = (
            expected_points
            + frame["gameid"].map(game_shock)
            + rng.normal(0.0, 0.45, len(frame))
        )
        design = build_design(frame)
        offense_draws, net_draws = [], []
        for draw in range(draws):
            weights, _ = _draw_weights(design, 1_000 + repetition, draw)
            beta, _, _, _, _ = fit_weighted_zero_prior(design, config, weights)
            offense_draws.append(beta[player_index] * 100.0)
            net_draws.append((beta[player_index] - beta[n_players + player_index]) * 100.0)
        for offset, (values, truth) in enumerate(
            (
                (offense_draws, target[player_index] * 100.0),
                (net_draws, (target[player_index] - target[n_players + player_index]) * 100.0),
            )
        ):
            lower80, upper80 = np.quantile(values, [0.10, 0.90])
            lower95, upper95 = np.quantile(values, [0.025, 0.975])
            covered[2 * offset] += lower80 <= truth <= upper80
            covered[2 * offset + 1] += lower95 <= truth <= upper95

    coverage = covered / repetitions
    # Monte Carlo uncertainty is material at 24 outer repetitions. Require
    # directional nominal coverage instead of pretending this is a precision
    # calibration study; both 95% intervals must still cover more often than
    # their 80% counterparts.
    assert (coverage[[0, 2]] >= 0.65).all()
    assert (coverage[[1, 3]] >= 0.82).all()
    assert (coverage[[1, 3]] >= coverage[[0, 2]]).all()
